# Generated by Django 3.2.7 on 2021-12-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cantlib',
            field=models.BigIntegerField(default=0, max_length=2, verbose_name='Cantidad_Libros'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='is_superuser'),
        ),
    ]
