# Generated by Django 3.2.7 on 2021-12-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_App', '0002_auto_20211207_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.CharField(default='False', max_length=15, verbose_name='is_superuser'),
        ),
    ]
