# Generated by Django 3.2.7 on 2021-12-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_App', '0004_alter_user_cantlib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BigIntegerField(default=0, verbose_name='is_superuser'),
        ),
    ]
